services:
  mongo:
    image: mongo:6.0
    container_name: mongo-replica
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
  
  # zookeeper :

    # zookeeper:

    # kafka:

    # logStreamer:

    # kafkaUI:

